const galleryData = [
  {
    id: 1,
    bg: '/images/aztec-calendar.svg',
    img1: '/images/Mexico-1.JPG',
    img2: '/images/Mexico-2.JPG',
    img3: '/images/Mexico-3.jpg',
    img4: '/images/Mexico-4.jpg',
    img5: '/images/Mexico-Main-4.jpg',
    img6: '/images/Mexico-5.JPG',
    img7: '/images/Mexico-6.jpg',
    img8: '/images/Mexico-7.jpg',
    img9: '/images/Mexico-9.jpg',
  },
  {
    id: 2,
    bg: '/images/Cherry-Blossoms.svg',
    img1: '/images/Japan-God.JPG',
    img2: '/images/Japan-Kyoto.JPG',
    img3: '/images/Japan-Ramen.jpg',
    img4: '/images/Japan-Murakami.jpg',
    img5: '/images/Japan-Main.jpg',
    img6: '/images/Japan-Osaka.JPG',
    img7: '/images/zen.jpg',
    img8: '/images/Japan-peeps.jpg',
    img9: '/images/Japan-Shibuya.jpg',
  },
  {
    id: 3,
    bg: '/images/China-BG.jpg ',
    img1: '/images/China-1.JPG',
    img2: '/images/China-2.JPG',
    img3: '/images/China-3.jpg',
    img4: '/images/China-4.jpg',
    img5: '/images/China-Main.jpg',
    img6: '/images/China-5.JPG',
    img7: '/images/China-6.jpg',
    img8: '/images/China-7.jpg',
    img9: '/images/China-9.jpg',
  },
  {
    id: 4,
    bg: '/images/AUE-BG.jpg',
    img1: '/images/AUE-1.JPG',
    img2: '/images/AUE-2.JPG',
    img3: '/images/AUE-3.jpg',
    img4: '/images/AUE-4.jpg',
    img5: '/images/AUE-Main.jpg',
    img6: '/images/AUE-5.JPG',
    img7: '/images/AUE-6.jpg',
    img8: '/images/AUE-7.jpg',
    img9: '/images/AUE-8.jpg',
  },
  {
    id: 5,
    bg: '/images/PR-BG.jpg',
    img1: '/images/PR-1.JPG',
    img2: '/images/PR-2.JPG',
    img3: '/images/PR-3.jpg',
    img4: '/images/PR-4.jpg',
    img5: '/images/PR-Main.jpg',
    img6: '/images/PR-5.JPG',
    img7: '/images/PR-6.jpg',
    img8: '/images/PR-7.jpg',
    img9: '/images/PR-8.jpg',
  },
];

export default galleryData;
